<div id="<?php echo $this->id; ?>" class="steps-content">           
    <div class="row">
        <div class="col-md-12">  
            <div class = 'alert alert-default' role='alert'>                         
                <i class="fa fa-thumbs-o-up fa-5x fa-fw pull-left text-primary-custom"></i>
                <p id="finalization_success"><strong><?php echo $this->translate('tr_melistemplatingplugincreator_finalization_success_title') ?></strong></p>     
            </div>            
         </div>
    </div>        
</div>







   