<div class="tab-content variant-prices-forms">
    <div id="" class="tab-pane field-accordion active"> 
<?php
    $i=1;
    foreach($this->fieldFormArr as $fieldForm){
       ?>                    
            <div class="widget" data-toggle="collapse-widget" data-collapse-closed="<?=$i==1?'false':'true'?>">
                <div class="widget-head melis-primary-bg accordionTitle">
                    <h4 class="heading"><?='Field '.$i ?></h4>
                </div>
                <div class="widget-body <?=$i==1?'show':''?>">
                   <?php                  
                    $fieldForm->prepare();
                    $fieldForm->setAttribute('id', $fieldForm->getAttribute('id').'-'.$i);
                   
                    echo $this->form()->openTag($fieldForm);
                    echo $this->melisFieldCollection($fieldForm);
                    echo $this->form()->closeTag();
                ?>
                </div>
            </div> 

    <?php
         $i++;
    }    
?>
    </div>  
</div>