<div class="col-md-12"> 
    <?php
        $form = $this->stepForm['form1'];
        $form->prepare();       
        echo $this->form()->openTag($form);
    
        foreach ($form->getElements() As $key => $val) { ?>               
            <div class="form-group">                        
                <?php $required = '';
                if (!empty($val->getAttribute('required'))) {
                    $required = '<sup>*</sup>';
                }                 
                ?>

                <label class="d-flex flex-row justify-content-between" for="<?=$key?>">
                    <div class="label-text"><?=$val->getLabel().$required?></div>
                    <?php 
                        if (!empty($val->getOptions()['tooltip'])) { ?>
                            <div class="slider-open-tooltip">
                                 <i class="fa fa-info-circle fa-lg float-right tip-info" data-toggle="tooltip" data-placement="left" title="" data-original-title="<?= $this->translate($val->getOptions()['tooltip'])?>"></i>
                            </div>
                    <?php    }
                    ?>                    
                </label>                             
                                  
                <div class = "form-group input-group">
                    <input class="<?=$val->getAttribute('class')?>" type="<?=$val->getAttribute('type')?>" id="<?=$key?>" name="<?=$key?>" required="required" value="<?=$val->getValue()?>">
                </div>   
            </div>
    <?php }//end first foreach 

    echo $this->form()->closeTag();
?>

    <div id='field-form-div' class="tab-pane active"> 
        <?php 
            if (!empty($this->stepForm['fieldForm'])) {
                echo $this->partial('melis-templating-plugin-creator/partial/field-form', array(
                    'fieldFormArr' => $this->stepForm['fieldForm']                                     
                ));   
            }
        ?>
    </div>
</div>

<script>
    fieldFormInit();
    widgetCollapsibleInit();
</script>









   